# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DatabaseType: Sqlite

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0 (preview)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.100-preview.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
