name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DatabaseType: Sqlite

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.202
        
    - name: Display .NET info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Debug

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Debug
